### PR TITLE
Add osx-arm64/native

### PR DESCRIPTION
**Pull request by kaylumah**
Add build/lib/Release/arm64/libnfd.dylib

Followed instructions from https://github.com/milleniumbug/NativeFileDialogSharp/issues/1#issuecomment-1474521250

### CODE REVIEW

**Comment by IceReaper** [comment]
Would it be bloated to also add Linux arm64? :)

**Comment by milleniumbug** [comment]
Not much bloat involved to be honest, especially since users of the library can use appropriate options to not ship libraries for platforms they don't support;

The biggest issue that prevents me from merging this (and also adding support for linux-arm64) is that I have to recompile for every platform involved, as the osx-arm64 uses a newer version of the native library than the other platforms, and this will make for inconsistent behaviour between osx-x64 and osx-arm64.

Ideally this repo should
- either have a CI/CD setup so it can adapt to potential future changes to the native library
- or even delegate the responsibility of making shared libraries of the native code upstream

**Comment by IceReaper** [comment]
Good point on the CI solution. that would be to prefer. Im basicaly trying to use this library here https://github.com/OpenRA/OpenRA/pull/20789 which is blocked mostly due to the missing natives currently.

**Comment by kaylumah** [comment]
Could this be merged if we follow the same instruction on a ` osx-x64 ` or is it then still blocked for the diff between Mac and linux/windows?

**Comment by milleniumbug** [comment]
Been neglecting this one for a while, sorry about that.

Yeah, I'll need the osx-x64 version too as I lost my hackintosh virtual machine. I'll try to build Linux and Windows versions next weekend.

**Comment by kaylumah** [comment]
No problem at all :)
Unfortunately I no longer have a non-ARM Mac available, so I cannot provide the x64 MacOs binaries myself

**Pull request closed without merging**
